// This file is generated by scripts/generate-wedding-partner-images.mjs.
// Source: drive-download-20260429T023611Z-3-001

export interface WeddingPartnerImageSet {
  category: string;
  images: readonly string[];
}

export const WEDDING_PARTNER_IMAGE_SETS = {
  "그래머시코엑스": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/001-8c46123f/01.webp",
      "/images/wedding-partners/wedding-hall/001-8c46123f/02.webp",
      "/images/wedding-partners/wedding-hall/001-8c46123f/03.webp",
      "/images/wedding-partners/wedding-hall/001-8c46123f/04.webp",
      "/images/wedding-partners/wedding-hall/001-8c46123f/05.webp",
      "/images/wedding-partners/wedding-hall/001-8c46123f/06.webp"
    ]
  },
  "그랜드힐컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/01.webp",
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/02.webp",
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/03.webp",
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/04.webp",
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/05.webp",
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/06.webp",
      "/images/wedding-partners/wedding-hall/002-2d00b3fb/07.webp"
    ]
  },
  "노블레스웨딩컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/01.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/02.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/03.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/04.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/05.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/06.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/07.webp",
      "/images/wedding-partners/wedding-hall/003-ac7c6fff/08.webp"
    ]
  },
  "더바실리움": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/004-e5815269/01.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/02.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/03.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/04.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/05.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/06.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/07.webp",
      "/images/wedding-partners/wedding-hall/004-e5815269/08.webp"
    ]
  },
  "더센트럴웨딩홀": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/01.webp",
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/02.webp",
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/03.webp",
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/04.webp",
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/05.webp",
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/06.webp",
      "/images/wedding-partners/wedding-hall/005-db4a8a3d/07.webp"
    ]
  },
  "라마다송도호텔웨딩홀": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/006-6ea1d523/01.webp",
      "/images/wedding-partners/wedding-hall/006-6ea1d523/02.webp",
      "/images/wedding-partners/wedding-hall/006-6ea1d523/03.webp",
      "/images/wedding-partners/wedding-hall/006-6ea1d523/04.webp",
      "/images/wedding-partners/wedding-hall/006-6ea1d523/05.webp",
      "/images/wedding-partners/wedding-hall/006-6ea1d523/06.webp",
      "/images/wedding-partners/wedding-hall/006-6ea1d523/07.webp"
    ]
  },
  "라비니움": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/007-5dcc1334/01.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/02.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/03.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/04.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/05.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/06.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/07.webp",
      "/images/wedding-partners/wedding-hall/007-5dcc1334/08.webp"
    ]
  },
  "라이즈오토그래프컬렉션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/008-f7440cd7/01.webp",
      "/images/wedding-partners/wedding-hall/008-f7440cd7/02.webp",
      "/images/wedding-partners/wedding-hall/008-f7440cd7/03.webp",
      "/images/wedding-partners/wedding-hall/008-f7440cd7/04.webp",
      "/images/wedding-partners/wedding-hall/008-f7440cd7/05.webp",
      "/images/wedding-partners/wedding-hall/008-f7440cd7/06.webp",
      "/images/wedding-partners/wedding-hall/008-f7440cd7/07.webp"
    ]
  },
  "메리빌리아더프레스티지": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/009-21eb89a9/01.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/02.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/03.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/04.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/05.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/06.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/07.webp",
      "/images/wedding-partners/wedding-hall/009-21eb89a9/08.webp"
    ]
  },
  "베리컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/010-3b456620/01.webp",
      "/images/wedding-partners/wedding-hall/010-3b456620/02.webp",
      "/images/wedding-partners/wedding-hall/010-3b456620/03.webp",
      "/images/wedding-partners/wedding-hall/010-3b456620/04.webp",
      "/images/wedding-partners/wedding-hall/010-3b456620/05.webp",
      "/images/wedding-partners/wedding-hall/010-3b456620/06.webp",
      "/images/wedding-partners/wedding-hall/010-3b456620/07.webp"
    ]
  },
  "브라이드밸리": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/011-2e458fde/01.webp",
      "/images/wedding-partners/wedding-hall/011-2e458fde/02.webp",
      "/images/wedding-partners/wedding-hall/011-2e458fde/03.webp",
      "/images/wedding-partners/wedding-hall/011-2e458fde/04.webp",
      "/images/wedding-partners/wedding-hall/011-2e458fde/05.webp"
    ]
  },
  "빌라드아모르이천": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/012-86b24202/01.webp",
      "/images/wedding-partners/wedding-hall/012-86b24202/02.webp",
      "/images/wedding-partners/wedding-hall/012-86b24202/03.webp",
      "/images/wedding-partners/wedding-hall/012-86b24202/04.webp",
      "/images/wedding-partners/wedding-hall/012-86b24202/05.webp",
      "/images/wedding-partners/wedding-hall/012-86b24202/06.webp"
    ]
  },
  "빌라드지디안산": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/013-1e2c93cb/01.webp",
      "/images/wedding-partners/wedding-hall/013-1e2c93cb/02.webp",
      "/images/wedding-partners/wedding-hall/013-1e2c93cb/03.webp",
      "/images/wedding-partners/wedding-hall/013-1e2c93cb/04.webp",
      "/images/wedding-partners/wedding-hall/013-1e2c93cb/05.webp"
    ]
  },
  "서울드래곤시티": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/014-cad70375/01.webp",
      "/images/wedding-partners/wedding-hall/014-cad70375/02.webp",
      "/images/wedding-partners/wedding-hall/014-cad70375/03.webp",
      "/images/wedding-partners/wedding-hall/014-cad70375/04.webp",
      "/images/wedding-partners/wedding-hall/014-cad70375/05.webp",
      "/images/wedding-partners/wedding-hall/014-cad70375/06.webp",
      "/images/wedding-partners/wedding-hall/014-cad70375/07.webp"
    ]
  },
  "서울올림픽파크텔": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/015-4c0142c4/01.webp",
      "/images/wedding-partners/wedding-hall/015-4c0142c4/02.webp",
      "/images/wedding-partners/wedding-hall/015-4c0142c4/03.webp",
      "/images/wedding-partners/wedding-hall/015-4c0142c4/04.webp",
      "/images/wedding-partners/wedding-hall/015-4c0142c4/05.webp",
      "/images/wedding-partners/wedding-hall/015-4c0142c4/06.webp"
    ]
  },
  "소노휴양평컨벤션홀": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/016-06383aa1/01.webp",
      "/images/wedding-partners/wedding-hall/016-06383aa1/02.webp",
      "/images/wedding-partners/wedding-hall/016-06383aa1/03.webp",
      "/images/wedding-partners/wedding-hall/016-06383aa1/04.webp",
      "/images/wedding-partners/wedding-hall/016-06383aa1/05.webp",
      "/images/wedding-partners/wedding-hall/016-06383aa1/06.webp"
    ]
  },
  "스카이컨벤션웨딩홀": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/017-51dbd098/01.webp",
      "/images/wedding-partners/wedding-hall/017-51dbd098/02.webp",
      "/images/wedding-partners/wedding-hall/017-51dbd098/03.webp",
      "/images/wedding-partners/wedding-hall/017-51dbd098/04.webp",
      "/images/wedding-partners/wedding-hall/017-51dbd098/05.webp",
      "/images/wedding-partners/wedding-hall/017-51dbd098/06.webp",
      "/images/wedding-partners/wedding-hall/017-51dbd098/07.webp"
    ]
  },
  "시그니엘웨딩": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/018-44ed226b/01.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/02.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/03.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/04.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/05.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/06.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/07.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/08.webp",
      "/images/wedding-partners/wedding-hall/018-44ed226b/09.webp"
    ]
  },
  "아레나파크웨딩": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/01.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/02.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/03.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/04.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/05.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/06.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/07.webp",
      "/images/wedding-partners/wedding-hall/019-0aa4c4c9/08.webp"
    ]
  },
  "아르떼웨딩컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/020-f2ac9b56/01.webp",
      "/images/wedding-partners/wedding-hall/020-f2ac9b56/02.webp",
      "/images/wedding-partners/wedding-hall/020-f2ac9b56/03.webp",
      "/images/wedding-partners/wedding-hall/020-f2ac9b56/04.webp",
      "/images/wedding-partners/wedding-hall/020-f2ac9b56/05.webp",
      "/images/wedding-partners/wedding-hall/020-f2ac9b56/06.webp"
    ]
  },
  "아이티컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/021-5e75ad87/01.webp",
      "/images/wedding-partners/wedding-hall/021-5e75ad87/02.webp",
      "/images/wedding-partners/wedding-hall/021-5e75ad87/03.webp",
      "/images/wedding-partners/wedding-hall/021-5e75ad87/04.webp",
      "/images/wedding-partners/wedding-hall/021-5e75ad87/05.webp",
      "/images/wedding-partners/wedding-hall/021-5e75ad87/06.webp"
    ]
  },
  "월드컵컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/022-ccb2543b/01.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/02.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/03.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/04.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/05.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/06.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/07.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/08.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/09.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/10.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/11.webp",
      "/images/wedding-partners/wedding-hall/022-ccb2543b/12.webp"
    ]
  },
  "판교엔씨소프트컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/023-364a96e1/01.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/02.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/03.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/04.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/05.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/06.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/07.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/08.webp",
      "/images/wedding-partners/wedding-hall/023-364a96e1/09.webp"
    ]
  },
  "퍼스트가든": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/024-d53025f8/01.webp",
      "/images/wedding-partners/wedding-hall/024-d53025f8/02.webp",
      "/images/wedding-partners/wedding-hall/024-d53025f8/03.webp",
      "/images/wedding-partners/wedding-hall/024-d53025f8/04.webp",
      "/images/wedding-partners/wedding-hall/024-d53025f8/05.webp"
    ]
  },
  "페어몬트앰배서더서울": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/025-f3354ea4/01.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/02.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/03.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/04.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/05.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/06.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/07.webp",
      "/images/wedding-partners/wedding-hall/025-f3354ea4/08.webp"
    ]
  },
  "프라움": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/026-18041046/01.webp",
      "/images/wedding-partners/wedding-hall/026-18041046/02.webp",
      "/images/wedding-partners/wedding-hall/026-18041046/03.webp",
      "/images/wedding-partners/wedding-hall/026-18041046/04.webp",
      "/images/wedding-partners/wedding-hall/026-18041046/05.webp",
      "/images/wedding-partners/wedding-hall/026-18041046/06.webp"
    ]
  },
  "호텔icc웨딩홀": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/027-ef382454/01.webp",
      "/images/wedding-partners/wedding-hall/027-ef382454/02.webp",
      "/images/wedding-partners/wedding-hall/027-ef382454/03.webp",
      "/images/wedding-partners/wedding-hall/027-ef382454/04.webp",
      "/images/wedding-partners/wedding-hall/027-ef382454/05.webp",
      "/images/wedding-partners/wedding-hall/027-ef382454/06.webp",
      "/images/wedding-partners/wedding-hall/027-ef382454/07.webp"
    ]
  },
  "휘겸재": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/01.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/02.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/03.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/04.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/05.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/06.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/07.webp",
      "/images/wedding-partners/wedding-hall/028-ecdcae7c/08.webp"
    ]
  },
  "cn천년부페웨딩홀주안점": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/029-9b9e5296/01.webp",
      "/images/wedding-partners/wedding-hall/029-9b9e5296/02.webp",
      "/images/wedding-partners/wedding-hall/029-9b9e5296/03.webp",
      "/images/wedding-partners/wedding-hall/029-9b9e5296/04.webp",
      "/images/wedding-partners/wedding-hall/029-9b9e5296/05.webp"
    ]
  },
  "dmc타워웨딩": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/030-ff1f3def/01.webp",
      "/images/wedding-partners/wedding-hall/030-ff1f3def/02.webp",
      "/images/wedding-partners/wedding-hall/030-ff1f3def/03.webp",
      "/images/wedding-partners/wedding-hall/030-ff1f3def/04.webp",
      "/images/wedding-partners/wedding-hall/030-ff1f3def/05.webp"
    ]
  },
  "ict밸리컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/031-406506cb/01.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/02.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/03.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/04.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/05.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/06.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/07.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/08.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/09.webp",
      "/images/wedding-partners/wedding-hall/031-406506cb/10.webp"
    ]
  },
  "w스퀘어컨벤션": {
    "category": "웨딩홀",
    "images": [
      "/images/wedding-partners/wedding-hall/032-b943d45a/01.webp",
      "/images/wedding-partners/wedding-hall/032-b943d45a/02.webp",
      "/images/wedding-partners/wedding-hall/032-b943d45a/03.webp",
      "/images/wedding-partners/wedding-hall/032-b943d45a/04.webp",
      "/images/wedding-partners/wedding-hall/032-b943d45a/05.webp",
      "/images/wedding-partners/wedding-hall/032-b943d45a/06.webp"
    ]
  },
  "더플랜업의원": {
    "category": "피부과",
    "images": [
      "/images/wedding-partners/dermatology/033-fa716cb9/01.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/02.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/03.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/04.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/05.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/06.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/07.webp",
      "/images/wedding-partners/dermatology/033-fa716cb9/08.webp"
    ]
  },
  "리셋의원분당": {
    "category": "피부과",
    "images": [
      "/images/wedding-partners/dermatology/034-f44baabe/01.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/02.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/03.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/04.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/05.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/06.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/07.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/08.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/09.webp",
      "/images/wedding-partners/dermatology/034-f44baabe/10.webp"
    ]
  },
  "샤인의원논현": {
    "category": "피부과",
    "images": [
      "/images/wedding-partners/dermatology/035-edcf8a56/01.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/02.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/03.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/04.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/05.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/06.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/07.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/08.webp",
      "/images/wedding-partners/dermatology/035-edcf8a56/09.webp"
    ]
  },
  "포엔의원강남점": {
    "category": "피부과",
    "images": [
      "/images/wedding-partners/dermatology/036-4e911ba2/01.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/02.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/03.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/04.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/05.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/06.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/07.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/08.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/09.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/10.webp",
      "/images/wedding-partners/dermatology/036-4e911ba2/11.webp"
    ]
  },
  "황금희에스테틱청담본점": {
    "category": "피부과",
    "images": [
      "/images/wedding-partners/dermatology/037-25f3c1d5/01.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/02.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/03.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/04.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/05.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/06.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/07.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/08.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/09.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/10.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/11.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/12.webp",
      "/images/wedding-partners/dermatology/037-25f3c1d5/13.webp"
    ]
  },
  "데이뷰의원": {
    "category": "피부과",
    "images": [
      "/images/wedding-partners/dermatology/dayview-clinic/01.webp",
      "/images/wedding-partners/dermatology/dayview-clinic/02.webp",
      "/images/wedding-partners/dermatology/dayview-clinic/03.webp",
      "/images/wedding-partners/dermatology/dayview-clinic/04.webp"
    ]
  },
  "라스트노트필름": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/038-4c719c6f/01.webp",
      "/images/wedding-partners/dvd/038-4c719c6f/02.webp",
      "/images/wedding-partners/dvd/038-4c719c6f/03.webp",
      "/images/wedding-partners/dvd/038-4c719c6f/04.webp",
      "/images/wedding-partners/dvd/038-4c719c6f/05.webp",
      "/images/wedding-partners/dvd/038-4c719c6f/06.webp"
    ]
  },
  "라이크필름": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/039-ecf6b107/01.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/02.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/03.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/04.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/05.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/06.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/07.webp",
      "/images/wedding-partners/dvd/039-ecf6b107/08.webp"
    ]
  },
  "룩어라운드필름": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/040-c0335ab3/01.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/02.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/03.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/04.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/05.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/06.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/07.webp",
      "/images/wedding-partners/dvd/040-c0335ab3/08.webp"
    ]
  },
  "비바그라피": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/041-db5ca6ca/01.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/02.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/03.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/04.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/05.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/06.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/07.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/08.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/09.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/10.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/11.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/12.webp",
      "/images/wedding-partners/dvd/041-db5ca6ca/13.webp"
    ]
  },
  "필름인데이": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/042-a150a73c/01.webp",
      "/images/wedding-partners/dvd/042-a150a73c/02.webp",
      "/images/wedding-partners/dvd/042-a150a73c/03.webp",
      "/images/wedding-partners/dvd/042-a150a73c/04.webp",
      "/images/wedding-partners/dvd/042-a150a73c/05.webp",
      "/images/wedding-partners/dvd/042-a150a73c/06.webp",
      "/images/wedding-partners/dvd/042-a150a73c/07.webp",
      "/images/wedding-partners/dvd/042-a150a73c/08.webp",
      "/images/wedding-partners/dvd/042-a150a73c/09.webp",
      "/images/wedding-partners/dvd/042-a150a73c/10.webp"
    ]
  },
  "필름한즈": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/043-05998782/01.webp",
      "/images/wedding-partners/dvd/043-05998782/02.webp",
      "/images/wedding-partners/dvd/043-05998782/03.webp",
      "/images/wedding-partners/dvd/043-05998782/04.webp",
      "/images/wedding-partners/dvd/043-05998782/05.webp",
      "/images/wedding-partners/dvd/043-05998782/06.webp",
      "/images/wedding-partners/dvd/043-05998782/07.webp"
    ]
  },
  "weddingstc": {
    "category": "DVD",
    "images": [
      "/images/wedding-partners/dvd/044-0a238253/01.webp",
      "/images/wedding-partners/dvd/044-0a238253/02.webp",
      "/images/wedding-partners/dvd/044-0a238253/03.webp",
      "/images/wedding-partners/dvd/044-0a238253/04.webp",
      "/images/wedding-partners/dvd/044-0a238253/05.webp",
      "/images/wedding-partners/dvd/044-0a238253/06.webp",
      "/images/wedding-partners/dvd/044-0a238253/07.webp",
      "/images/wedding-partners/dvd/044-0a238253/08.webp"
    ]
  },
  "나비아스튜디오": {
    "category": "스튜디오",
    "images": [
      "/images/wedding-partners/studio/045-91fda3f0/01.webp",
      "/images/wedding-partners/studio/045-91fda3f0/02.webp",
      "/images/wedding-partners/studio/045-91fda3f0/03.webp",
      "/images/wedding-partners/studio/045-91fda3f0/04.webp",
      "/images/wedding-partners/studio/045-91fda3f0/05.webp",
      "/images/wedding-partners/studio/045-91fda3f0/06.webp",
      "/images/wedding-partners/studio/045-91fda3f0/07.webp",
      "/images/wedding-partners/studio/045-91fda3f0/08.webp"
    ]
  },
  "다다스튜디오": {
    "category": "스튜디오",
    "images": [
      "/images/wedding-partners/studio/046-d5e4b931/01.webp",
      "/images/wedding-partners/studio/046-d5e4b931/02.webp",
      "/images/wedding-partners/studio/046-d5e4b931/03.webp",
      "/images/wedding-partners/studio/046-d5e4b931/04.webp",
      "/images/wedding-partners/studio/046-d5e4b931/05.webp",
      "/images/wedding-partners/studio/046-d5e4b931/06.webp",
      "/images/wedding-partners/studio/046-d5e4b931/07.webp",
      "/images/wedding-partners/studio/046-d5e4b931/08.webp"
    ]
  },
  "로이스튜디오": {
    "category": "스튜디오",
    "images": [
      "/images/wedding-partners/studio/047-bb6cb1d8/01.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/02.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/03.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/04.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/05.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/06.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/07.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/08.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/09.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/10.webp",
      "/images/wedding-partners/studio/047-bb6cb1d8/11.webp"
    ]
  },
  "에반스스튜디오": {
    "category": "스튜디오",
    "images": [
      "/images/wedding-partners/studio/048-bf508965/01.webp",
      "/images/wedding-partners/studio/048-bf508965/02.webp",
      "/images/wedding-partners/studio/048-bf508965/03.webp",
      "/images/wedding-partners/studio/048-bf508965/04.webp",
      "/images/wedding-partners/studio/048-bf508965/05.webp"
    ]
  },
  "청스튜디오": {
    "category": "스튜디오",
    "images": [
      "/images/wedding-partners/studio/049-d5582d0f/01.webp",
      "/images/wedding-partners/studio/049-d5582d0f/02.webp",
      "/images/wedding-partners/studio/049-d5582d0f/03.webp",
      "/images/wedding-partners/studio/049-d5582d0f/04.webp",
      "/images/wedding-partners/studio/049-d5582d0f/05.webp",
      "/images/wedding-partners/studio/049-d5582d0f/06.webp",
      "/images/wedding-partners/studio/049-d5582d0f/07.webp",
      "/images/wedding-partners/studio/049-d5582d0f/08.webp",
      "/images/wedding-partners/studio/049-d5582d0f/09.webp",
      "/images/wedding-partners/studio/049-d5582d0f/10.webp"
    ]
  },
  "프로필라이즈": {
    "category": "스튜디오",
    "images": [
      "/images/wedding-partners/studio/050-57dbdcae/01.webp",
      "/images/wedding-partners/studio/050-57dbdcae/02.webp",
      "/images/wedding-partners/studio/050-57dbdcae/03.webp",
      "/images/wedding-partners/studio/050-57dbdcae/04.webp",
      "/images/wedding-partners/studio/050-57dbdcae/05.webp",
      "/images/wedding-partners/studio/050-57dbdcae/06.webp",
      "/images/wedding-partners/studio/050-57dbdcae/07.webp",
      "/images/wedding-partners/studio/050-57dbdcae/08.webp"
    ]
  },
  "몬트샤인": {
    "category": "드레스",
    "images": [
      "/images/wedding-partners/dress/051-e5353bf7/01.webp",
      "/images/wedding-partners/dress/051-e5353bf7/02.webp",
      "/images/wedding-partners/dress/051-e5353bf7/03.webp",
      "/images/wedding-partners/dress/051-e5353bf7/04.webp",
      "/images/wedding-partners/dress/051-e5353bf7/05.webp",
      "/images/wedding-partners/dress/051-e5353bf7/06.webp",
      "/images/wedding-partners/dress/051-e5353bf7/07.webp",
      "/images/wedding-partners/dress/051-e5353bf7/08.webp",
      "/images/wedding-partners/dress/051-e5353bf7/09.webp",
      "/images/wedding-partners/dress/051-e5353bf7/10.webp",
      "/images/wedding-partners/dress/051-e5353bf7/11.webp",
      "/images/wedding-partners/dress/051-e5353bf7/12.webp"
    ]
  },
  "앨리브라이덜인천점": {
    "category": "드레스",
    "images": [
      "/images/wedding-partners/dress/052-d700ce6b/01.webp",
      "/images/wedding-partners/dress/052-d700ce6b/02.webp",
      "/images/wedding-partners/dress/052-d700ce6b/03.webp",
      "/images/wedding-partners/dress/052-d700ce6b/04.webp",
      "/images/wedding-partners/dress/052-d700ce6b/05.webp",
      "/images/wedding-partners/dress/052-d700ce6b/06.webp",
      "/images/wedding-partners/dress/052-d700ce6b/07.webp",
      "/images/wedding-partners/dress/052-d700ce6b/08.webp",
      "/images/wedding-partners/dress/052-d700ce6b/09.webp",
      "/images/wedding-partners/dress/052-d700ce6b/10.webp",
      "/images/wedding-partners/dress/052-d700ce6b/11.webp",
      "/images/wedding-partners/dress/052-d700ce6b/12.webp",
      "/images/wedding-partners/dress/052-d700ce6b/13.webp"
    ]
  },
  "제이엔부띠끄": {
    "category": "드레스",
    "images": [
      "/images/wedding-partners/dress/053-dce707f1/01.webp",
      "/images/wedding-partners/dress/053-dce707f1/02.webp",
      "/images/wedding-partners/dress/053-dce707f1/03.webp",
      "/images/wedding-partners/dress/053-dce707f1/04.webp",
      "/images/wedding-partners/dress/053-dce707f1/05.webp"
    ]
  },
  "쥬시드레스": {
    "category": "드레스",
    "images": [
      "/images/wedding-partners/dress/054-a9546b90/01.webp",
      "/images/wedding-partners/dress/054-a9546b90/02.webp",
      "/images/wedding-partners/dress/054-a9546b90/03.webp",
      "/images/wedding-partners/dress/054-a9546b90/04.webp",
      "/images/wedding-partners/dress/054-a9546b90/05.webp",
      "/images/wedding-partners/dress/054-a9546b90/06.webp",
      "/images/wedding-partners/dress/054-a9546b90/07.webp"
    ]
  },
  "다교청담": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/055-80eb4e51/01.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/02.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/03.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/04.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/05.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/06.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/07.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/08.webp",
      "/images/wedding-partners/hair-makeup/055-80eb4e51/09.webp"
    ]
  },
  "더블앤": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/056-8620cde3/01.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/02.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/03.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/04.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/05.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/06.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/07.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/08.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/09.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/10.webp",
      "/images/wedding-partners/hair-makeup/056-8620cde3/11.webp"
    ]
  },
  "디데이헤어메이크업": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/057-612d5801/01.webp",
      "/images/wedding-partners/hair-makeup/057-612d5801/02.webp",
      "/images/wedding-partners/hair-makeup/057-612d5801/03.webp",
      "/images/wedding-partners/hair-makeup/057-612d5801/04.webp",
      "/images/wedding-partners/hair-makeup/057-612d5801/05.webp",
      "/images/wedding-partners/hair-makeup/057-612d5801/06.webp",
      "/images/wedding-partners/hair-makeup/057-612d5801/07.webp"
    ]
  },
  "르보청담": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/058-7235e68a/01.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/02.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/03.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/04.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/05.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/06.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/07.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/08.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/09.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/10.webp",
      "/images/wedding-partners/hair-makeup/058-7235e68a/11.webp"
    ]
  },
  "리즈뷰티강남본점": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/059-7185b359/01.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/02.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/03.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/04.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/05.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/06.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/07.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/08.webp",
      "/images/wedding-partners/hair-makeup/059-7185b359/09.webp"
    ]
  },
  "뷰티플로우": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/01.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/02.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/03.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/04.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/05.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/06.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/07.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/08.webp",
      "/images/wedding-partners/hair-makeup/060-fbdb51ef/09.webp"
    ]
  },
  "브랜미": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/01.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/02.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/03.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/04.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/05.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/06.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/07.webp",
      "/images/wedding-partners/hair-makeup/061-5ff1ff23/08.webp"
    ]
  },
  "영뷰티메이크업": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/062-3b368a3b/01.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/02.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/03.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/04.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/05.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/06.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/07.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/08.webp",
      "/images/wedding-partners/hair-makeup/062-3b368a3b/09.webp"
    ]
  },
  "제니하우스": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/063-70ea4053/01.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/02.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/03.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/04.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/05.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/06.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/07.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/08.webp",
      "/images/wedding-partners/hair-makeup/063-70ea4053/09.webp"
    ]
  },
  "제이솜메이크업": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/064-d3f70f46/01.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/02.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/03.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/04.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/05.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/06.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/07.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/08.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/09.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/10.webp",
      "/images/wedding-partners/hair-makeup/064-d3f70f46/11.webp"
    ]
  },
  "the화사메이크업": {
    "category": "메이크업",
    "images": [
      "/images/wedding-partners/hair-makeup/065-b4f22903/01.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/02.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/03.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/04.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/05.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/06.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/07.webp",
      "/images/wedding-partners/hair-makeup/065-b4f22903/08.webp"
    ]
  },
  "더버리엔스냅": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/066-658a7da2/01.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/02.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/03.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/04.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/05.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/06.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/07.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/08.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/09.webp",
      "/images/wedding-partners/ceremony-snap/066-658a7da2/10.webp"
    ]
  },
  "디아필름": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/067-6b21070a/01.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/02.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/03.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/04.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/05.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/06.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/07.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/08.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/09.webp",
      "/images/wedding-partners/ceremony-snap/067-6b21070a/10.webp"
    ]
  },
  "루이루체": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/068-b7504298/01.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/02.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/03.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/04.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/05.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/06.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/07.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/08.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/09.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/10.webp",
      "/images/wedding-partners/ceremony-snap/068-b7504298/11.webp"
    ]
  },
  "르모망": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/069-ce45c738/01.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/02.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/03.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/04.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/05.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/06.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/07.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/08.webp",
      "/images/wedding-partners/ceremony-snap/069-ce45c738/09.webp"
    ]
  },
  "베르엔느": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/070-069f238f/01.webp",
      "/images/wedding-partners/ceremony-snap/070-069f238f/02.webp",
      "/images/wedding-partners/ceremony-snap/070-069f238f/03.webp",
      "/images/wedding-partners/ceremony-snap/070-069f238f/04.webp",
      "/images/wedding-partners/ceremony-snap/070-069f238f/05.webp",
      "/images/wedding-partners/ceremony-snap/070-069f238f/06.webp",
      "/images/wedding-partners/ceremony-snap/070-069f238f/07.webp"
    ]
  },
  "업라이트본식스냅": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/01.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/02.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/03.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/04.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/05.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/06.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/07.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/08.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/09.webp",
      "/images/wedding-partners/ceremony-snap/071-3d0a5bf9/10.webp"
    ]
  },
  "오브로즈": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/072-95848223/01.webp",
      "/images/wedding-partners/ceremony-snap/072-95848223/02.webp",
      "/images/wedding-partners/ceremony-snap/072-95848223/03.webp",
      "/images/wedding-partners/ceremony-snap/072-95848223/04.webp",
      "/images/wedding-partners/ceremony-snap/072-95848223/05.webp",
      "/images/wedding-partners/ceremony-snap/072-95848223/06.webp"
    ]
  },
  "이플스냅": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/01.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/02.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/03.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/04.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/05.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/06.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/07.webp",
      "/images/wedding-partners/ceremony-snap/073-c3343a0f/08.webp"
    ]
  },
  "체리쉬스냅": {
    "category": "스냅",
    "images": [
      "/images/wedding-partners/ceremony-snap/074-662fec9c/01.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/02.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/03.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/04.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/05.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/06.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/07.webp",
      "/images/wedding-partners/ceremony-snap/074-662fec9c/08.webp"
    ]
  }
} as const satisfies Record<string, WeddingPartnerImageSet>;

export function normalizeWeddingPartnerName(value?: string | null) {
  return String(value || '')
    .normalize('NFC')
    .toLowerCase()
    .replace(/[()[\]{}（）]/g, '')
    .replace(/주식회사|유한회사|\(주\)|㈜/g, '')
    .replace(/[\s·ㆍ.,'"\`~!@#$%^&*_+=/\\|:;?<>-]/g, '');
}

export function getWeddingPartnerImageSet(...names: Array<string | null | undefined>) {
  const imageSets = WEDDING_PARTNER_IMAGE_SETS as Record<string, WeddingPartnerImageSet>;
  const keys = Object.keys(imageSets);

  for (const name of names) {
    const normalized = normalizeWeddingPartnerName(name);
    if (!normalized) continue;
    const exact = imageSets[normalized];
    if (exact) return exact;

    if (normalized.length >= 4) {
      const looseMatches = keys.filter((key) => (
        key.length >= 4 && (key.includes(normalized) || normalized.includes(key))
      ));
      if (looseMatches.length === 1) return imageSets[looseMatches[0]];
    }
  }

  return undefined;
}

export function getWeddingPartnerImages(...names: Array<string | null | undefined>) {
  return getWeddingPartnerImageSet(...names)?.images || [];
}

export function getWeddingPartnerCategory(...names: Array<string | null | undefined>) {
  return getWeddingPartnerImageSet(...names)?.category;
}

export function getWeddingPartnerSectionCategories(imageSet?: WeddingPartnerImageSet) {
  const categories = imageSet?.category ? [imageSet.category] : [];
  if (imageSet?.images.some((image) => image.includes('/hair-makeup/'))) {
    categories.push('헤어', '메이크업');
  }

  return Array.from(new Set(categories.filter(Boolean)));
}

export function mergeWeddingPartnerImages(...groups: Array<ReadonlyArray<string | null | undefined> | undefined>) {
  const seen = new Set<string>();
  const merged: string[] = [];

  for (const group of groups) {
    if (!Array.isArray(group)) continue;
    for (const image of group) {
      if (!image || seen.has(image)) continue;
      seen.add(image);
      merged.push(image);
    }
  }

  return merged;
}
